apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 087439572472.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 087439572472.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 273c7610
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
